language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - cd frontend
script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh_token
  local_dir: frontend/build
  target_branch: gh-pages
  keep_history: true
  on:
    branch: master
